apiVersion: scheduler.kalypso.io/v1alpha1
kind: SchedulingPolicy
metadata:
  name: red-policy
spec:
  deploymentTargetSelector:    
    labelSelector:
      matchLabels:
        zone: red
        application: control-tower
  clusterTypeSelector:
    labelSelector: 
      matchLabels:
        zone: red
