apiVersion: scheduler.kalypso.io/v1alpha1
kind: BaseRepo
metadata:
  name: main
spec:
  repo: https://github.com/eedorenko/kalypso-demo-control-plane
  branch: main
  path: .
  commit: c80328cb9eab9cba07470a99da53ab5300b11590
