apiVersion: scheduler.kalypso.io/v1alpha1
kind: Environment
metadata:
  name: newenv
spec:
  controlPlane:
    repo: https://github.com/eedorenko/kalypso-demo-control-plane
    branch: newenv
    path: .
