apiVersion: v1
kind: ConfigMap
metadata:
  name: burger-detection-platform-config-union-square
  labels:
     platform-config: "true"
     task: burger-detection
     brand: cke
     store: union-square
data:
  worker_cameras: |
    '["packaging2"]'
  worker_zones: |
    '["packaging2/assembly_table"]'
  worker_zones_zone_boundary_threshold: "8 pixels"
  worker_zones_rentry_buffer_time: "5s"

    
