apiVersion: v1
kind: ConfigMap
metadata:
  name: eu-config
  labels:
     platform-config: "true"
     region: eu
data:
  REGION: EU
  DATABASE_URL: mysql://eu-db-host:3308/mysql
  keyvaultName: ansible-secret-key-vault
  azureTenantId: 16b3c013-d300-468d-ac64-7eda0820b6d3
  secretObjects: |
          - type: Opaque
            data:
            - sourcePath: application-secret
              targetKey: application-secret-value
  keyVaultSecrets: |
              - |
                objectName: application-secret
                objectType: secret


  
  
