apiVersion: scheduler.kalypso.io/v1alpha1
kind: ClusterType
metadata:
  name: eu
  labels: 
    region: eu
    zone: gray
spec:
  reconciler: arc-flux
  namespaceService: default
  configType: configmap
