apiVersion: scheduler.kalypso.io/v1alpha1
kind: WorkloadRegistration
metadata:
  name: controltower
  labels:
    type: application
spec:
  workload:
    repo: https://github.com/eedorenko/control-tower
    branch: main
    path: ./workload
  workspace: demo-team
