apiVersion: scheduler.kalypso.io/v1alpha1
kind: ClusterType
metadata:
  name: cke
  labels: 
    brand: cke
    people_detection: "true"
    burger_detection: "true"
    fry_warmer_estimation: "true"
spec:
  reconciler: arc-flux
  namespaceService: default
  configType: configmap
