apiVersion: scheduler.kalypso.io/v1alpha1
kind: Template
metadata:
  labels:
  name: default
spec:
  type: namespace
  manifests:
    - |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ .Namespace}}" 
        labels:
          environment: "{{ .Environment}}"
          workspace: "{{ .Workspace}}"
          workload: "{{ .Workload}}"
          deploymentTarget: "{{ .DeploymentTargetName}}"
          someLabel: some-value
    - |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ .Workload}}-sa"
        namespace: "{{ .Namespace}}"
      {{if .ConfigData.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .ConfigData.imagePullSecrets }}
      {{end}}
    - |
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: pvc-limit-range
        namespace: "{{ .Namespace}}"
        labels:
          environment: "{{ .Environment}}"
          workload: "{{ .Workload}}"
      spec:
        limits:
        - max:
            storage: 64Gi
          min:
            storage: 1Gi
          type: PersistentVolumeClaim
    - |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: pvc-resource-quota
        namespace: "{{ .Namespace}}"
        labels:
          environment: "{{ .Environment}}"
          workload: "{{ .Workload}}"
      spec:
        hard:
          requests.storage: 64Gi
    - |
      apiVersion: secrets-store.csi.x-k8s.io/v1
      kind: SecretProviderClass
      metadata:
        name: "{{ .Workload}}-spc"
        namespace: "{{ .Namespace}}"
        labels:
          environment: "{{ .Environment}}"
          workload: "{{ .Workload}}"
      spec:
        provider: azure        
        parameters:
          clientID: "{{ .ConfigData.managedIdentityId}}"
          keyvaultName: "{{ .ConfigData.keyvaultName}}"
          objects: |
            array:
      {{ toYaml .ConfigData.keyVaultSecrets | indent 10}}
          tenantID: "{{ .ConfigData.azureTenantId}}"
    - |
      {{if .ConfigData.secretObjects }}
      {{$namespace := print .Namespace }}
      {{$name := print .Workload "-secret-sync" }}
      {{$serviceAccountName := print .Workload "-sa" }}
      {{$secretProviderClassName := print .Workload "-spc" }}      
      {{range $h := .ConfigData.secretObjects}}
      apiVersion: secret-sync.x-k8s.io/v1alpha1
      kind: SecretSync
      metadata:
        name: {{ $name }}
        namespace: {{ $namespace }}
      spec:
        serviceAccountName: "{{ $serviceAccountName }}"
        secretProviderClassName: "{{ $secretProviderClassName }}"
        secretObject:
          type: "{{ $h.type}}"
          data: 
      {{ toYaml $h.data | indent 6}}
      {{end}}  
      {{end}}
